root_dir: mbatch_test

globals:
  global: data/globals.yml

gitcheck_pkgs:
  - numpy
  - healpy
#  - pymaster

stages:
  # Compute mask's mode-coupling matrix (MCM)
  mcm:
    exec: python3
    script: pipeline/mcmer.py
    globals:
      - global
    options:
      # Directory to store MCM
      # absolute path or path relative to mbatch output directory
      mcm-dir: results/mcm

  # Filter all power-law sims
  filter_PL:
    exec: python3
    script: pipeline/filterer_mcut.py
    globals:
      - global
    options:
      # Directory containing all input maps
      sim-dir: data/PL
      # Directory to store filtered maps
      # absolute path or path relative to mbatch output directory
      filtered-dir: results/filtered
      binary-mask-file: data/mask_binary.fits
      m-cut: 30

  # Filter all validation sims
  filter_val:
    exec: python3
    script: pipeline/filterer_mcut.py
    globals:
      - global
    options:
      # Directory containing all validation input maps
      sim-dir: data/val
      # Directory to store validation filtered maps
      # absolute path or path relative to mbatch output directory
      filtered-dir: results/filtered_val
      binary-mask-file: data/mask_binary.fits
      m-cut: 30

  # Compute pseudo-Cl of input power-law sims
  pcl_PL_in:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    options:
      first-sim: 0
      num-sims: 200
      sim-sorter: pl_sim_names_EandB
      sim-type: input

  # Compute pseudo-Cl of filtered power-law sims
  pcl_PL_filt:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    depends:
      - filter_PL
    options:
      first-sim: 0
      num-sims: 200
      sim-sorter: pl_sim_names_EandB
      sim-type: filtered

  # Compute pseudo-Cl of input validation sims
  pcl_val_in:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    options:
      first-sim: 0
      num-sims: 200
      sim-sorter: val_sim_names
      sim-type: input

  # Compute pseudo-Cl of filtered validation sims
  pcl_val_filt:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    depends:
      - filter_val
    options:
      first-sim: 0
      num-sims: 200
      sim-sorter: val_sim_names
      sim-type: filtered

  # Estimate transfer function and bandpower
  # window functions from PL sim products
  transfer:
    exec: python3
    script: pipeline/transfer.py
    globals:
      - global
    depends:
      - mcm
      - pcl_PL_in
      - pcl_PL_filt
    options:
      use-theory: True

  # Compute Cl of filtered validation sims
  # corrected for the transfer function
  cl_val:
    exec: python3
    script: pipeline/pcler.py
    globals:
      - global
    depends:
      - filter_val
      - transfer
    options:
      first-sim: 0
      num-sims: 200
      sim-sorter: val_sim_names
      sim-type: decoupled
      correct-transfer: True

  # Compare Cl of validation sims with theory
  # convolved with bpw window functions
  transfer_val:
    exec: python3
    script: pipeline/transfer_validator.py
    globals:
      - global
    depends:
      - pcl_val_in
      - pcl_val_filt
      - transfer
      - cl_val
    options:
      transfer-threshold: 0.05
